name: sem-viz-jupyter
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - tensorflow=2.1.0
  - tensorflow-estimator=2.1.0
  - numpy=1.19.2
  - joblib
  - scipy
  - scikit-learn=1.0.2
  - pandas
  - matplotlib
  - colorcet
  - seaborn
  - pyyaml
  - yacs
  - tqdm
  - colorama
  - cython
  - coloredlogs
  - colorlog
  - gensim=3.8.0
  - opencv=3.4.2
  - statsmodels
  - ipython
  - jupyter
  - jupyterlab
  - nodejs
  - jupytext
  - pip
  - panel
  - holoviews
  - plotly
  - python-kaleido
  - hvplot
  - pip:
      - protobuf==3.20.1
      - vidgear
      - ray[default]==1.8.0
