name: sem-37
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - opencv
  - pandas
  - ipywidgets
  - jupyterlab
  - jupyter
  - nodejs
  - ipywebrtc
  - scikit-video
  - matplotlib
  - seaborn
  - nodejs
