name: process-feature
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - joblib
  - scipy
  - scikit-learn=1.0.2
  - pandas
  - matplotlib
  - colorcet
  - seaborn
  - pyyaml
  - yacs
  - tqdm
  - colorama
  - cython
  - coloredlogs
  - colorlog
  - gensim=3.8.0
  - opencv=3.4.2
  - statsmodels
  - ipython
  - jupyter
  - jupyterlab
  - nodejs
  - jupytext
  - pip
  - panel
  - holoviews
  - plotly
  - python-kaleido
  - hvplot
  - pip:
      - protobuf==3.20.1
