name: pt-37
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - pytorch
  - cuda92
  - torchvision
  - scipy=1.4.1
  - scikit-learn=0.23.2
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - pyyaml
  - yacs
  - tqdm
  - colorama
  - cython
  - tensorboardX
  - coloredlogs
  - colorlog
  - gensim=3.8.0
  - opencv
  - panel
  - statsmodels
