name: sem-viz-jupyter-frozen
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.3.0
  - absl-py=0.15.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - astor=0.8.1
  - async-timeout=4.0.2
  - asynctest=0.13.0
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=2.11
  - bleach=4.1.0
  - blinker=1.4
  - bokeh=2.3.3
  - bottleneck=1.3.4
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15.1
  - cachetools=4.2.2
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - colorama=0.4.4
  - colorcet=2.0.6
  - coloredlogs=15.0.1
  - colorlog=5.0.1
  - cryptography=3.4.8
  - cycler=0.11.0
  - cython=0.29.28
  - dataclasses=0.8
  - dbus=1.13.18
  - debugpy=1.5.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - expat=2.4.4
  - ffmpeg=4.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-forge=1
  - fonttools=4.25.0
  - freeglut=3.0.0
  - freetype=2.11.0
  - frozenlist=1.2.0
  - gast=0.2.2
  - gensim=3.8.0
  - giflib=5.2.1
  - glib=2.69.1
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - grpcio=1.42.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.8.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - holoviews=1.14.5
  - humanfriendly=10.0
  - hvplot=0.7.3
  - icu=58.2
  - idna=3.3
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - importlib_resources=5.2.0
  - ipykernel=6.9.1
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jasper=2.0.14
  - jedi=0.18.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.2.2
  - jupyter_console=6.4.3
  - jupyter_core=4.10.0
  - jupyter_server=1.13.5
  - jupyterlab=3.3.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.12.0
  - jupyterlab_widgets=1.0.0
  - jupytext=1.14.0
  - kaleido-core=0.2.1
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.3
  - libgcc=7.2.0
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglu=9.0.0
  - libgomp=9.3.0
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libopenblas=0.3.6
  - libopencv=3.4.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.19.1
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markdown-it-py=2.1.0
  - markupsafe=2.0.1
  - mathjax=2.7.7
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - mdit-py-plugins=0.3.0
  - mdurl=0.1.0
  - mistune=0.8.4
  - multidict=5.2.0
  - munkres=1.1.4
  - nbclassic=0.3.5
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nodejs=6.13.1
  - notebook=6.4.8
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.1
  - numpy=1.19.2
  - numpy-base=1.19.2
  - oauthlib=3.2.0
  - opencv=3.4.2
  - openssl=1.1.1n
  - opt_einsum=3.3.0
  - packaging=21.3
  - pandas=1.3.5
  - pandocfilters=1.5.0
  - panel=0.11.3
  - param=1.12.0
  - parso=0.8.3
  - patsy=0.5.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=21.2.2
  - pixman=0.40.0
  - plotly=5.6.0
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - protobuf=3.19.1
  - ptyprocess=0.7.0
  - py-opencv=3.4.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyct=0.4.8
  - pygments=2.11.2
  - pyjwt=2.1.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.7.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - python-kaleido=0.2.1
  - pytz=2021.3
  - pyviz_comms=2.0.2
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qt=5.9.7
  - qtconsole=5.3.0
  - qtpy=2.0.1
  - readline=8.1.2
  - requests=2.27.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-learn=0.23.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - send2trash=1.8.0
  - setuptools=61.2.0
  - sip=4.19.8
  - six=1.16.0
  - smart_open=5.2.1
  - sniffio=1.2.0
  - soupsieve=2.3.1
  - sqlite=3.38.2
  - statsmodels=0.12.2
  - tenacity=8.0.1
  - tensorboard=2.4.0
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.1.0
  - tensorflow-base=2.1.0
  - tensorflow-estimator=2.1.0
  - termcolor=1.1.0
  - terminado=0.13.1
  - testpath=0.5.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - toml=0.10.2
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.1.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - urllib3=1.26.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.0.3
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - wrapt=1.13.3
  - xz=5.2.5
  - yacs=0.1.6
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - blessed==1.19.1
    - colorful==0.5.4
    - decorator==4.4.2
    - deprecated==1.2.13
    - filelock==3.6.0
    - google-api-core==2.7.3
    - googleapis-common-protos==1.56.0
    - gpustat==1.0.0b1
    - hiredis==2.0.0
    - imageio==2.21.2
    - imageio-ffmpeg==0.4.7
    - moviepy==1.0.3
    - msgpack==1.0.3
    - nvidia-ml-py3==7.352.0
    - opencensus==0.9.0
    - opencensus-context==0.1.2
    - proglog==0.1.10
    - psutil==5.9.0
    - py-spy==0.3.11
    - ray==1.8.0
    - redis==4.2.2
    - vidgear==0.2.6

