name: pt-tf-37
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - tensorflow=2.1.0
  - tensorboard=2.1.1
  - pytorch=0.4.1
  - torchvision
  - scipy=1.4.1
  - scikit-learn=0.23.2
  - numpy=1.19.2
  - pandas
  - ipywidgets
  - jupyterlab
  - jupyter
  - nodejs
  - ipywebrtc
  - matplotlib
  - seaborn
  - nodejs
  - pyyaml
  - yacs
  - tqdm
  - colorama
  - cython
  - tensorboardX
  - coloredlogs
  - colorlog
  - gensim
  - opencv
  - panel
  - statsmodels
