name: process-feature
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - joblib
  - scipy
  - scikit-learn=0.23.2
  - pandas
  - matplotlib
  - colorcet
  - seaborn
  - pyyaml
  - yacs
  - tqdm
  - colorama
  - cython
  - coloredlogs
  - colorlog
  - gensim=3.8.0
  - opencv
  - statsmodels
  - ipython
  - jupyter
  - plotly
  - pip
  