name: sem-37
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - tensorflow=2.1.0
  - pytorch=0.4.1
  - torchvision
  - opencv
  - scipy
  - scikit-learn
  - pandas
  - ipywidgets
  - jupyterlab
  - jupyter
  - nodejs
  - ipywebrtc
  - matplotlib
  - seaborn
  - nodejs
  - pyyaml
  - yacs
  - tqdm
  - colorama
  - cython
  - tensorboardX
  - coloredlogs
  - colorlog
  - gensim
  - numpy
