name: sem-viz-jupyter
channels:
  - defaults
  - conda-forge
dependencies:
  - tensorflow
  - numpy
  - joblib
  - scipy
  - scikit-learn
  - pandas
  - matplotlib
  - colorcet
  - seaborn
  - pyyaml
  - yacs
  - tqdm
  - colorama
  - cython
  - coloredlogs
  - colorlog
  - opencv
  - statsmodels
  - ipython
  - jupyter
  - plotly
  - pip
  - pip:
      - protobuf
      - ray[default]
