[Appear]
;run=1.1.1_kinect
;run=output/track_kinect_complete.txt
run=1.2.3_C1
input_csv_tracking=output/tracking/1.2.3_C1_r50.csv
;input_csv_tracking=data/merged/6.2.4_C1_merged.csv
output_csv_appear=output/appear/
feature_tag=oct_23_24
